name: Go pipeline test

on:
  push:
    branches: ["main"]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'      # You can change this version as needed
        cache: true
    - name: Check go version
      run: go version

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./handlers

    - name: Build the server
      run: go build -o my-app ./server  # Adjust the main file name if different
    
    - name: docker image build
      run: docker build -t sreekuttan121/testing_repo:v1 .

    - name: docker login
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: docker image push
      run: docker push sreekuttan121/testing_repo:v1