name: Go pipeline test

on:
  push:
    branches: ["main"]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'      # You can change this version as needed
        cache: true
    - name: Check go version
      run: go version

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./handlers

    - name: Build the server
      run: go build -o my-app ./server  # Adjust the main file name if different
    
    - name: docker image build
      run: docker build -t sreekuttan121/testing_repo:v1 .

    - name: docker login
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: docker image push
      run: docker push sreekuttan121/testing_repo:v1
  
  ec2-deployment:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Step 1 - Install Docker on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo usermod -a -G docker ec2-user
            fi

      - name: Step 2 - Login to Docker Hub
        uses: appleboy/ssh-action@v1
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: DOCKER_USERNAME,DOCKER_PASSWORD
          script: |
            echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Step 3 - Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker pull sreekuttan121/testing_repo:v1
            sudo docker stop my-go-app || true
            sudo docker rm my-go-app || true
            sudo docker run -d -p 8080:8080 --name my-go-app sreekuttan121/testing_repo:v1 